const ArabicLang = {};
const EnglishLang = {
  SIGN_IN: "SIGN IN",
  ADD_NOTE_FOR_NOW: "ADD NOTE FOR NOW",
  SIGN_IN_WITH_EMAIL: "SIGN IN WITH EMAIL",
  FORGOT_PASSWORD: "FORGOT YOUR PASSWORD",
  CONTINUE_WITH: "CONTINUE WITH",
  GOOGLE: "GOOGLE",
  DONT_HAVE_ACCOUNT: "don't have an account?",
  NEVER_MIND_STATEMENT:
    "Nevermind, just add your email & password. And the account will be created immmediately.",
  GOOGLE: "GOOGLE",
  EMAIL: "EMAIL",
  PASSWORD: "PASSWORD",
  SIGN_IN: "SIGN IN",
  RESET_PASSWORD: "RESET PASSWORD",
  ENTER_YOUR_EMAIL: "Enter your Email",
  ENTER_NEW_PASSWORD: "Enter your new password",
  RE_ENTER_PASSWORD: "Re-enter Password",
  SEND_EMAIL: "SEND EMAIL",
  MY_NOTES: "MY NOTES",
  LATEST: "LATEST",
  SECTIONS: "SECTIONS",
  CREATE_A_NEW_NOTE: "CREATE NOTE",
  HEADLINE: "HEADLINE",
  DESCRIPTION: "DESCRIPTION",
  SECTION: "SECTION",
  NONE: "None",
  ADD_NOTE: "ADD NOTE",
  COLOR: "color",
  DELETE: "delete",
  EDIT: "edit",
  NOTE: "NOTE",
  APPEND_TO_THIS_NOTE: "Append to this note",
};

export { EnglishLang, ArabicLang };
